### PR TITLE
Better match info

### LINKED ISSUE #227: Accept rule match locations
# Why?
This will be more helpful for debugging rules as well as providing more information for readers of our reports.

# What/How?
Add a JSON column to `scans` to hold all the match information. This will also make the `package_rules` and `rules` table irrelevant.

Also, the `POST /package` endpoint should be modified to use this new column, and the Pydantic model should be updated too.

### PR DESCRIPTION
**Pull request by Robin5605**
Closes #227 

Add a `files` column to the database of type JSONB that can store detailed match information, including spans and data as bytes.

### CODE REVIEW

**Review by jonathan-d-zhang — CHANGES_REQUESTED** [review]
We can add indexes on this new column later depending on what queries we need. Chances are we are still only going to be querying based on the already indexed columns.

**Review by jonathan-d-zhang — DISMISSED** [review]
lgtm :shipit:

**Comment by Robin5605** [comment]
todo: modify schema to accept distribution information

**Comment by jonathan-d-zhang** [comment]
untodo: we will just include the distribution in the file name

**Comment by Robin5605** [comment]
todo: update schema docs

**Review by jonathan-d-zhang — APPROVED** [review]

**Pull request merged**
