### PR TITLE
Add coverage.py

### PR DESCRIPTION
**Pull request by AbooMinister25**

### CODE REVIEW

**Review by shenanigansd — CHANGES_REQUESTED** [review]
Lets use a `[tool.coverage]` section in our `pyproject.toml` instead of an extra `.coveragerc` file.

**Review by Robin5605 — CHANGES_REQUESTED** [review]
Can you add the following files to `omit`?
```
    src/mainframe/dependencies.py
    src/mainframe/database.py
    src/mainframe/json_web_token.py
    src/mainframe/custom_exceptions.py
    src/mainframe/utils/microsoft.py
    src/mainframe/utils/mailer.py
```
I think these are files that are either not really worth testing or are going to be difficult to test meaningfully, and is going to bring down our coverage rate.

**Comment by Robin5605** [comment]
We should probably also disable branch checking for now, would bring it up to 100% (since coveragepy reports some partials that are hard to work around)

**Review by Robin5605 — APPROVED** [review]
:ship:

**Review by shenanigansd — APPROVED** [review]
:shipit:

**Pull request merged**
