### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by shenanigansd**
Add a license now that the repo is open source.

All existing contributors, please approve as consent to apply the license.

### CODE REVIEW

**Review by Robin5605 — APPROVED** [review]
lgtm :shipit:

**Review by import-pandas-as-numpy — APPROVED** [review]
LGTM :shipit:

**Review by SwiftNathalie — APPROVED** [review]
LGTM :shipit:

**Review by jonathan-d-zhang — APPROVED** [review]
:shipit:

**Review by AbooMinister25 — APPROVED** [review]
LGTM

**Review by sid-maddy — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
